name: Build and Push to ICR

on:
  push:
    branches:
      - main

jobs:
  app:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Build and Push to ICR
      id: build-step
      uses: IBM/code-engine-github-action@v1
      with:
        api-key: ${{ secrets.IBM_IAM_API_KEY }}
        region: 'ca-tor'
        project: 'gh-action-test-proj'
        component: 'build'
        name: 'my-ce-app'
        image: private.ca.icr.io/gh-a-lr/hello-node:latest
        registry-secret: ce-auto-icr-private-ca-tor
        build-source: './my-ce-app'

    - name: se image with digest
      run: | 
        echo "Image with digest: ${{ steps.build-step.outputs.image-with-digest }}"