name: Build and Push to ICR

on:
  push:
    branches:
      - main

jobs:
  app:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Build and Push to ICR
      uses: ./.github/actions/ce-action
      with:
        api-key: ${{ secrets.IBM_IAM_API_KEY }}
        region: 'ca-tor'
        project: 'gh-action-test-proj'
        component: 'build'
        name: 'my-ce-app'
        image: private.ca.icr.io/gh-a-lr/hello-node:latest
        registry-secret: ce-auto-icr-private-ca-tor
        build-source: './my-ce-app'